//***Language Change***Buttons1****************************************//

  document.getElementById('buttons1').addEventListener('click', function (event) {var language = event.target.id.substr('button-'.length);地図1.setLayoutProperty('country-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('state-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('settlement-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('settlement-subdivision-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('airport-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('poi-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('water-point-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('water-line-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('natural-point-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('natrual-line-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('waterway-label', 'text-field', ['get','name_' + language]);地図1.setLayoutProperty('road-label', 'text-field', ['get','name_' + language]);});

//***Language Change***Buttons2****************************************//

  document.getElementById('buttons2').addEventListener('click', function (event) {var language = event.target.id.substr('button-'.length);地図2.setLayoutProperty('country-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('state-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('settlement-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('settlement-subdivision-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('airport-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('poi-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('water-point-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('water-line-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('natural-point-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('natrual-line-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('waterway-label', 'text-field', ['get','name_' + language]);地図2.setLayoutProperty('road-label', 'text-field', ['get','name_' + language]);});

  //*********************************************************************//
  //*********************************************************************//
  //*********************************************************************//
  //*********************************************************************//
